### ISSUE TITLE
slangroom-editor The error slangroom are gone ;(

### ISSUE THREAD

**Issue by puria** [dyne/components#13]
Now everything is in a red box without no breaks... very hard to read.
To reproduce try to change the contract in the homepage of dyne.org/slangroom and run it with wrong contract

**Comment by matteo-cristino** [comment]
For me now it has the correct color

![image](https://github.com/user-attachments/assets/01601842-8c4d-417a-ac06-0f55e1d0667e)

Can you post your contract?

**Comment by puria** [comment]
![Uploading Screenshot.from.2024-07-23.at.14_38_27.236421255.png…]()

**Comment by matteo-cristino** [comment]
Really strange, I tried it, but I always see it as in my above screenshot. But I discover another bug, if you reload enoguh time (like 3,4 times) the homepage at a certain point the `keys` section will disappear (as shown in Puria screenshot).
