### ISSUE TITLE
New component Slangroom-editor examplse loader

### ISSUE THREAD

**Issue by puria** [dyne/components#9]
One component should be created to allow to read and load inside the editor some examples:

```html
<dyne-slangroom-preset-loader target-id="editor" folder="./examples" />
<dyne-slangroom-editor id="editor">
</dyne-slangroom-editor>
```
I envision something like the code before.

The examples can also be written as slot inside like:

```html
<dyne-slangroom-preset-loader>
  <dyne-slangroom-preset id=`` conrtact=`` data=`` keys=`` title=`` description=`` group=``></dyne-slangroom-preset>
</dyne-slangroom-preset-loader>

```

**Comment by bbtgnn** [comment]
Can i add https://github.com/dyne/slangroom/tree/main/docs/examples as submodule of this repo?

**Comment by bbtgnn** [comment]
@puria  I am using degit to clone only the examples, I added a npm script
